name: Publish CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*' ]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to docker
        env:
          DOCKER_USER: rzuckerm
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USER}" --password-stdin

      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: ${VERSION}
          echo "VERSION=${VERSION}" >>${GITHUB_ENV}
          echo "DOCKER_TAG_SUFFIX=-${VERSION}" >>${GITHUB_ENV}

      - name: Show tag
        run: |
          echo "Tag (without v) is ${VERSION}"
          echo "Docker tag suffix is ${DOCKER_TAG_SUFFIX}"

      - name: Build images
        run: make build

      - name: Test images
        run: make test

      - name: Publish images
        run: make publish
